---
title: "JJiang_HW5"
author: "Joe Jiang"
date: "December 7, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Question 1

```{r popular baby names in 2016} 
infantName <- read.table('yob2016.txt',sep = ';')#load the file 
colnames(infantName)<- c('FirstName','Gender','NumberofChildren') #rename the columns
summary(infantName)
str(infantName)
grep('yyy$',infantName$FirstName, value = TRUE)#find the name ends with "yyy"
y2016 <- infantName[infantName$FirstName!='Fionayyy',] #remove the name fom the table and rename the table as 'y2016'
```
### Question 2
```{r popular baby names in 2015}
y2015 <- read.table('yob2015.txt',sep = ',')#load the file 
colnames(y2015)<- c('FirstName','Gender','NumberofChildren') #rename the columns
tail(y2015, 10)
```

**From the last 10 rows, we can speculate that the table is likely sorted in the order of gender, number of children and first name.** 

```{r merge two tables}
final <- merge(y2016, y2015, by= c("FirstName","Gender"))
names(final) <- c('FirstName','Gender','2016','2015')
```
### Question 3
```{r toal amount of children born with the same name in 2015 and 2016 }
final$Total <- final$'2015' + final$'2016' #combine the amount of children born in 2015 and 2016
paste0("The total number of children with popular names = ", sum(final$Total)) 
final <- final[order(final$Total, decreasing = TRUE),] #sort the table by total amount of children
head(final, 10) #display the top ten popular names
write.csv(head(final[final$Gender =='F',c("FirstName","Total")], 10), 'Top10GirlNames.csv', row.names = FALSE)
```




